package main

import (
	"fmt"
	"os"
	"time"
)

func handleAnalytics() {
	fmt.Println("🌐 Generating Multi-Repo Analytics Dashboard...")

	repos := getRepoList()
	if len(repos) == 0 {
		fmt.Println("No repositories configured to generate dashboard.")
		return
	}

	htmlContent := `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GitFlowPro Enterprise Dashboard</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #0d1117; color: #c9d1d9; padding: 2rem; margin: 0; }
        h1 { color: #58a6ff; text-align: center; font-size: 2.5rem; text-transform: uppercase; letter-spacing: 2px; }
        .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 1.5rem; margin-top: 2rem; }
        .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; box-shadow: 0 4px 6px rgba(0,0,0,0.3); transition: transform 0.2s; }
        .card:hover { transform: translateY(-5px); border-color: #58a6ff; }
        .repo-name { font-size: 1.2rem; font-weight: bold; color: #58a6ff; margin-bottom: 1rem; word-break: break-all; }
        .stat { display: flex; justify-content: space-between; margin-bottom: 0.5rem; font-size: 1.1rem; }
        .stat-value { font-weight: bold; color: #3fb950; }
        .footer { text-align: center; margin-top: 3rem; color: #8b949e; font-size: 0.9rem; }
    </style>
</head>
<body>
    <h1>GitFlowPro Command Center</h1>
    <p style="text-align: center; color: #8b949e;">Live Analytics for ` + fmt.Sprintf("%d", len(repos)) + ` Repositories</p>
    <div class="grid">`

	token := os.Getenv("GH_TOKEN")
	for _, repo := range repos {
		issues := 0
		prs := 0
		if token != "" {
			// Best effort fetch
			if issuesData, err := fetchGitHubData(fmt.Sprintf("https://api.github.com/repos/%s/issues?state=open", repo), token); err == nil {
				issues = len(issuesData)
			}
			if prsData, err := fetchGitHubData(fmt.Sprintf("https://api.github.com/repos/%s/pulls?state=open", repo), token); err == nil {
				prs = len(prsData)
			}
		}

		htmlContent += fmt.Sprintf(`
        <div class="card">
            <div class="repo-name">📁 %s</div>
            <div class="stat"><span>Open Issues</span> <span class="stat-value">%d</span></div>
            <div class="stat"><span>Open PRs</span> <span class="stat-value">%d</span></div>
        </div>`, repo, issues, prs)
	}

	htmlContent += `
    </div>
    <div class="footer">Generated by GitFlowPro • ` + time.Now().UTC().Format(time.RFC1123) + `</div>
</body>
</html>`

	err := os.WriteFile("dashboard.html", []byte(htmlContent), 0644)
	if err != nil {
		fmt.Printf("❌ Failed to generate dashboard: %v\n", err)
		return
	}

	fmt.Println("✅ Dashboard successfully generated: dashboard.html")
}
