import os
import requests
import sys

# Configuration
GITHUB_TOKEN = os.getenv("GH_TOKEN")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
REPO = os.getenv("REPO_NAME")
PR_NUMBER = os.getenv("PR_NUMBER")

headers = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

def get_pr_diff():
    url = f"https://api.github.com/repos/{REPO}/pulls/{PR_NUMBER}"
    headers_diff = headers.copy()
    headers_diff["Accept"] = "application/vnd.github.v3.diff"
    r = requests.get(url, headers=headers_diff)
    r.raise_for_status()
    return r.text

def generate_ai_summary(diff):
    if not OPENAI_API_KEY:
        return "⚠️ OpenAI API Key missing. Unable to generate AI summary."

    # Heuristic fallback if diff is too large or for demonstration
    if len(diff) > 20000:
        diff = diff[:20000] + "\n... (diff truncated)"

    prompt = f"""
Analyze the following git diff and provide a structured PR summary:
1. **What changed**: High-level overview.
2. **Risk level**: Low, Medium, or High with reasoning.
3. **Files affected**: List of key files.
4. **Suggested tests**: What should the reviewer focus on testing?

Diff:
{diff}
"""

    # In a real scenario, we would call OpenAI API here.
    # For this toolkit, we'll provide the logic to call it if the key is present.
    try:
        response = requests.post(
            "https://api.openai.com/v1/chat/completions",
            headers={"Authorization": f"Bearer {OPENAI_API_KEY}"},
            json={
                "model": "gpt-3.5-turbo",
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.7
            },
            timeout=30
        )
        response.raise_for_status()
        return response.json()['choices'][0]['message']['content']
    except Exception as e:
        return f"❌ AI Summary Error: {str(e)}\n\n(Fallback: Manual review required for this large diff)"

def post_comment(body):
    url = f"https://api.github.com/repos/{REPO}/issues/{PR_NUMBER}/comments"
    r = requests.post(url, headers=headers, json={"body": body})
    r.raise_for_status()

def main():
    if not GITHUB_TOKEN or not REPO or not PR_NUMBER:
        print("Missing environment variables.")
        sys.exit(1)

    print(f"Generating AI Summary for PR #{PR_NUMBER}...")
    diff = get_pr_diff()
    summary = generate_ai_summary(diff)
    
    full_comment = f"""### 🤖 GitFlowPro AI PR Insights

{summary}

---
*Generated by GitFlowPro AI Automation*"""

    post_comment(full_comment)
    print("AI Summary posted successfully.")

if __name__ == "__main__":
    main()
